=== Mohamedfawzy1993/BFDA_Chat/Client/src/main/java/xmlfiles/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="messages">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="message" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="from" type="xs:string" />
						<!--<xs:element name="to" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>-->
						<xs:element name="date" type="xs:string" />
						<xs:element name="content" type="xs:string" >
							<xs:attribute name="color" type="xs:string" default="#000"/>
							<xs:attribute name="font-size" type="xs:string" default="15"/>
							<xs:attribute name="font-family" type="xs:string" default="calibri"/>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
        <xs:attribute name="owner" type="xs:string" default="None"/>
        <xs:attribute name="chatName" type="xs:string" default="None"/>
</xs:element>
</xs:schema>

=== Mohamedfawzy1993/BFDA_Chat/Client/src/main/java/xmlfiles/Ahmedahmed_Gamal_1518967073049.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="xmlStyle.xsl"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" owner="Ahmedahmed" chatName="Gamal">
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:17:19</date>
<content color="#000000ff" font-size="15" font-family="Arial">hello</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:17:27</date>
<content color="#000000ff" font-size="15" font-family="Arial">eh r2yk</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:21:01</date>
<content color="#80801aff" font-size="17" font-family="Vivaldi Italic">SQWS</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:21:38</date>
<content color="#80801aff" font-size="13" font-family="Vivaldi Italic">QWSWQS</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:21:40</date>
<content color="#80801aff" font-size="13" font-family="Vivaldi Italic">WSQS</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:21:52</date>
<content color="#80801aff" font-size="13" font-family="Verdana Bold Italic"></content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:21:59</date>
<content color="#80801aff" font-size="13" font-family="Algerian">WQSWQS</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:22:02</date>
<content color="#80801aff" font-size="13" font-family="Algerian"></content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:22:04</date>
<content color="#80801aff" font-size="13" font-family="Algerian"></content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T13:40:32</date>
<content color="#000000ff" font-size="15" font-family="Arial">fsfsd</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-16T14:01:48</date>
<content color="#000000ff" font-size="15" font-family="Arial">Hello All</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-16T14:01:52</date>
<content color="#000000ff" font-size="15" font-family="Arial">gred</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T14:02:30</date>
<content color="#000000ff" font-size="15" font-family="Arial">gasfdfedrqew</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T18:11:06</date>
<content color="#000000ff" font-size="15" font-family="Arial">sdfds</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T18:11:10</date>
<content color="#000000ff" font-size="15" font-family="Arial">sfsd</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-16T18:11:12</date>
<content color="#000000ff" font-size="15" font-family="Arial">fdsfsdf</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T00:41:42</date>
<content color="#000000ff" font-size="15" font-family="Arial">dsfdsa</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T00:41:44</date>
<content color="#000000ff" font-size="15" font-family="Arial">fdsf</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T00:43:15</date>
<content color="#000000ff" font-size="15" font-family="Arial">fdfsd</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-18T01:55:22</date>
<content color="#000000ff" font-size="15" font-family="Arial">Hello World :D</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-18T01:55:28</date>
<content color="#000000ff" font-size="15" font-family="Arial">Hello World</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-18T01:55:52</date>
<content color="#000000ff" font-size="15" font-family="Arial">Dd</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-18T01:55:55</date>
<content color="#000000ff" font-size="15" font-family="Arial">Hello world</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T18:49:47</date>
<content color="#000000ff" font-size="15" font-family="Arial">ghjkl</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T18:49:53</date>
<content color="#000000ff" font-size="15" font-family="Arial">cgvbhjnmk,</content>
</message>
<message>
<from>Ahmedahmed</from>
<date>2018-02-18T18:49:57</date>
<content color="#000000ff" font-size="15" font-family="Arial">vgbhjnkl</content>
</message>
<message>
<from>Gamal</from>
<date>2018-02-18T19:15:46</date>
<content color="#000000ff" font-size="15" font-family="Arial">7amadaaaaaaaaa</content>
</message>
</messages>
